unit ParticleLocator;
//
// Particle Locator (generated by GitHub CoPilot)
// 10.03.26

interface

uses
  System.SysUtils,
  System.Generics.Collections;

type

   TImageArray = array of array of Word;

  // Record to store particle information
  TParticle = record
    ID: Integer;
    Centroid_X: Double;
    Centroid_Y: Double;
    Area: Integer;
    BoundingBox_Left: Integer;
    BoundingBox_Top: Integer;
    BoundingBox_Right: Integer;
    BoundingBox_Bottom: Integer;
    Pixels: TArray<TPair<Integer, Integer>>; // Array of (X, Y) coordinates
  end;

  // Array of particles
  TParticleArray = TArray<TParticle>;

  // Particle locator class
  TParticleLocator = class
  private
    FImage: TArray<TArray<UInt16>>;
    FWidth: Integer;
    FHeight: Integer;
    FVisited: TArray<TArray<Boolean>>;
    FParticles: TParticleArray;

    procedure InitializeVisited;
    procedure FloodFill(X, Y: Integer; ParticleID: Integer; var Pixels: TList<TPair<Integer, Integer>>);
    function IsValidPixel(X, Y: Integer): Boolean;

  public
    constructor Create(Image: TArray<TArray<UInt16>>; Width, Height: Integer);
    destructor Destroy; override;

    procedure LocateParticles( ErosionRadius: UInt16 );
    function GetParticles: TParticleArray;
    function GetParticleCount: Integer;

    procedure ApplyErosionWithRadius(var Image: TArray<TArray<UInt16>>; {TImageArray;} Width, Height, Radius: Integer);

  end;

implementation

{ TParticleLocator }

constructor TParticleLocator.Create(Image: TArray<TArray<UInt16>>; Width, Height: Integer);
begin
  inherited Create;
  FImage := Image;
  FWidth := Width;
  FHeight := Height;
  InitializeVisited;
end;

destructor TParticleLocator.Destroy;
begin
  inherited;
end;

procedure TParticleLocator.InitializeVisited;
var
  I, J: Integer;
begin
  SetLength(FVisited, FHeight, FWidth);
  for I := 0 to FHeight - 1 do
    for J := 0 to FWidth - 1 do
      FVisited[I, J] := False;
end;

function TParticleLocator.IsValidPixel(X, Y: Integer): Boolean;
begin
  Result := (X >= 0) and (X < FWidth) and (Y >= 0) and (Y < FHeight);
end;

procedure TParticleLocator.FloodFill(X, Y: Integer; ParticleID: Integer;
  var Pixels: TList<TPair<Integer, Integer>>);
var
  Queue: TQueue<TPair<Integer, Integer>>;
  Current: TPair<Integer, Integer>;
  DX, DY: Integer;
  NewX, NewY: Integer;
  Directions: array[0..3] of TPair<Integer, Integer>;
  I: Integer;
begin
  Queue := TQueue<TPair<Integer, Integer>>.Create;
  try
    // Define 4-connectivity directions (up, down, left, right)
    Directions[0] := TPair<Integer, Integer>.Create(0, -1);  // Up
    Directions[1] := TPair<Integer, Integer>.Create(0, 1);   // Down
    Directions[2] := TPair<Integer, Integer>.Create(-1, 0);  // Left
    Directions[3] := TPair<Integer, Integer>.Create(1, 0);   // Right

    Queue.Enqueue(TPair<Integer, Integer>.Create(X, Y));
    FVisited[Y, X] := True;

    while Queue.Count > 0 do
    begin
      Current := Queue.Dequeue;
      Pixels.Add(Current);

      // Check all 4 neighbors
      for I := 0 to 3 do
      begin
        DX := Directions[I].Key;
        DY := Directions[I].Value;
        NewX := Current.Key + DX;
        NewY := Current.Value + DY;

        if IsValidPixel(NewX, NewY) and not FVisited[NewY, NewX] and
           (FImage[NewY, NewX] > 0) then
        begin
          FVisited[NewY, NewX] := True;
          Queue.Enqueue(TPair<Integer, Integer>.Create(NewX, NewY));
        end;
      end;
    end;
  finally
    Queue.Free;
  end;
end;

procedure TParticleLocator.LocateParticles(ErosionRadius: UInt16);
var
  X, Y: Integer;
  ParticleID: Integer;
  iRadius : Integer ;
  Pixels: TList<TPair<Integer, Integer>>;
  Particle: TParticle;
  Pixel: TPair<Integer, Integer>;
  MinX, MaxX, MinY, MaxY: Integer;
  SumX, SumY: Int64;
begin

  for IRadius := 1 to ErosionRadius do
      begin
      ApplyErosionWithRadius( FImage, FWidth, FHeight, 1 );
      end;

  SetLength(FParticles, 0);
  InitializeVisited;

  ParticleID := 0;

  for Y := 0 to FHeight - 1 do
  begin
    for X := 0 to FWidth - 1 do
    begin
      // Check if pixel is above threshold and not visited
      if (FImage[Y, X] > 0) and not FVisited[Y, X] then
      begin
        Pixels := TList<TPair<Integer, Integer>>.Create;
        try
          // Perform flood fill to find all connected pixels
          FloodFill(X, Y, ParticleID, Pixels);

          if Pixels.Count > 0 then
          begin
            // Initialize particle record
            Particle.ID := ParticleID;
            Particle.Area := Pixels.Count;

            // Calculate bounding box and centroid
            MinX := Pixels[0].Key;
            MaxX := Pixels[0].Key;
            MinY := Pixels[0].Value;
            MaxY := Pixels[0].Value;
            SumX := 0;
            SumY := 0;

            for Pixel in Pixels do
            begin
              if Pixel.Key < MinX then MinX := Pixel.Key;
              if Pixel.Key > MaxX then MaxX := Pixel.Key;
              if Pixel.Value < MinY then MinY := Pixel.Value;
              if Pixel.Value > MaxY then MaxY := Pixel.Value;

              Inc(SumX, Pixel.Key);
              Inc(SumY, Pixel.Value);
            end;

            Particle.BoundingBox_Left := MinX;
            Particle.BoundingBox_Top := MinY;
            Particle.BoundingBox_Right := MaxX;
            Particle.BoundingBox_Bottom := MaxY;

            Particle.Centroid_X := SumX / Pixels.Count;
            Particle.Centroid_Y := SumY / Pixels.Count;

            Particle.Pixels := Pixels.ToArray;

            // Add particle to array
            SetLength(FParticles, Length(FParticles) + 1);
            FParticles[High(FParticles)] := Particle;

            Inc(ParticleID);
          end;
        finally
          Pixels.Free;
        end;
      end;
    end;
  end;
end;

function TParticleLocator.GetParticles: TParticleArray;
begin
  Result := FParticles;
end;

function TParticleLocator.GetParticleCount: Integer;
begin
  Result := Length(FParticles);
end;


procedure TParticleLocator.ApplyErosionWithRadius(var Image: TArray<TArray<UInt16>>;{TImageArray;} Width, Height, Radius: Integer);
{
  ApplyErosionWithRadius - Applies erosion with a circular structuring element

  Parameters:
    Image: 2D array of 16-bit integers representing the binary image
    Width: Width of the image
    Height: Height of the image
    Radius: Radius of the erosion kernel

  Uses a circular structuring element (disk) for erosion.
}
var
  ResultImage: TArray<TArray<UInt16>>; //TImageArray;
  X, Y: Integer;
  DX, DY: Integer;
  ImageX, ImageY: Integer;
  MinValue: Word;
  Distance: Double;
  RadiusSq: Double;
begin
  if (Width <= 0) or (Height <= 0) or (Radius <= 0) then
    Exit;

  // Create result image with same dimensions
  SetLength(ResultImage, Height, Width);

  RadiusSq := Radius * Radius;

  try
    // Process each pixel in the image
    for Y := 0 to Height - 1 do
    begin
      for X := 0 to Width - 1 do
      begin
        // Initialize with maximum value
        MinValue := High(Word);

        // Apply circular structuring element
        for DY := -Radius to Radius do
        begin
          for DX := -Radius to Radius do
          begin
            // Check if point is within circular radius
            Distance := DX * DX + DY * DY;

            if Distance <= RadiusSq then
            begin
              // Calculate coordinates in the image
              ImageX := X + DX;
              ImageY := Y + DY;

              // Check boundaries
              if (ImageX >= 0) and (ImageX < Width) and
                 (ImageY >= 0) and (ImageY < Height) then
              begin
                // Update minimum value
                if Image[ImageY, ImageX] < MinValue then
                  MinValue := Image[ImageY, ImageX];
              end
              else
              begin
                // Boundary handling: treat as zero
                MinValue := 0;
              end;
            end;
          end;
        end;

        // Set the eroded value
        if MinValue = High(Word) then
          ResultImage[Y, X] := 0
        else
          ResultImage[Y, X] := MinValue;
      end;
    end;

    // Copy result back to original image
    Image := ResultImage;

  finally
    // Cleanup handled automatically
  end;
end;

end.
